on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        type: choice
        default: development
        options:
        - development
        - test
        - production
        - preproduction

jobs:
  Deploy:
    runs-on: ubuntu-latest
    name: Deploy Infra to AWS
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "files/lambda/requirements.txt"

      - name: terraform version
        run: terraform --version

      - name: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make  ${{ inputs.environment }} terraform-init

      - name: terraform validation
        run: terraform validate

      - name: terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make  ${{ inputs.environment }} terraform-apply

      - run: |
          echo The infrastructure has been deployed
